version: '3'

services:
  stockapp:
    build: .
    ports:
      - 8001:8001
    volumes:
      - ./:/usr/app
    depends_on:
      - stockapp-mysql
      - stockapp-redis

  stockapp-mysql:
    image: mariadb:10.3
    command: --innodb-use-native-aio=0
    restart: "no"
    ports:
      - 33006:3306
    volumes:
      - "./.docker/dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: stockapp
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
      MYSQL_ROOT_PASSWORD: root123

  stockapp-adminer:
    image: adminer:latest
    restart: "no"
    ports:
      - 8080:8080
    depends_on:
      - stockapp-mysql

  stockapp-redis:
    image: redis:alpine
    expose:
      - 6379
